# Generated by Django 4.1.1 on 2022-10-29 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        #('cars', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='u_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='Car_ID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='cars.cars'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Cus_ID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='home.customer'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='O_ID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='home.order'),
        ),
    ]
