# Generated by Django 4.1.1 on 2022-12-12 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_alter_customer_u_id_alter_order_car_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Cus_ID',
        ),
        migrations.AddField(
            model_name='order',
            name='id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
