# Generated by Django 4.1.1 on 2022-12-13 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_order_address_remove_order_cus_id_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('Car_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=30)),
                ('Brand', models.CharField(max_length=30)),
                ('Status', models.CharField(max_length=30)),
                ('Model', models.CharField(max_length=30)),
                ('Engine', models.CharField(max_length=30)),
                ('picture', models.ImageField(upload_to='')),
                ('Price', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='O_ID',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='payment',
        ),
        migrations.AlterField(
            model_name='order',
            name='Car_ID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='home.cars'),
        ),
    ]
