# Generated by Django 4.2.2 on 2023-09-17 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_rentcars_rental'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('P_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=30)),
                ('transaction_amount', models.CharField(max_length=30)),
                ('Date_time', models.DateTimeField()),
                ('Status', models.CharField(max_length=30)),
                ('Car_ID', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='home.cars')),
                ('id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
