# Generated by Django 4.2.5 on 2023-09-23 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_cars_transmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=20)),
                ('type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Sports', 'Sports'), ('Convertible', 'Convertible')], max_length=20)),
                ('brand', models.CharField(choices=[('Audi', 'Audi'), ('BMW', 'BMW'), ('Honda', 'Honda'), ('Land-Rover', 'Land-Rover'), ('Mercedes', 'Mercedes'), ('Toyota', 'Toyota')], max_length=20)),
                ('engine', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel')], max_length=20)),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('image', models.ImageField(upload_to='car_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='Car_ID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='home.car'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Car_ID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='home.car'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='Car_ID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='home.car'),
        ),
        migrations.DeleteModel(
            name='cars',
        ),
    ]
