# Generated by Django 4.1.1 on 2022-10-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('Car_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=30)),
                ('Brand', models.CharField(max_length=30)),
                ('Status', models.CharField(max_length=30)),
                ('Model', models.CharField(max_length=30)),
                ('Color', models.CharField(max_length=30)),
                ('picture', models.ImageField(upload_to='')),
                ('Price', models.FloatField()),
            ],
        ),
    ]
