# Generated by Django 4.1.1 on 2022-12-08 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='Color',
            new_name='Engine',
        ),
    ]
